backend: 
  name: git-gateway
  branch: master

media_folder: static/imgUploads
public_folder: /imgUploads

collections:
      - label: "Podcast Episodes"
        name: "podcast-episodes"
        identifier_field: name
        create: true
        folder: "content/podcastEpisodesFolder"
        media_library:
          config:
            multiple: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Serial, name: serial, widget: string}
          - {label: Number, name: number, widget: string}
          - {label: Description, name: descriptionText, widget: text}
          - {label: LongText, name: longText, widget: markdown}
          - {label: Date, name: date, widget: number}
          - {label: Month, name: month, widget: string}
          - label: Images 
            name: images 
            widget: list 
            fields:
            - {label: image, name: image, widget: image}
            - {label: Image description, name: alt, widget: text}
          - label: Tags 
            name: hashtags 
            widget: list 
            fields:
            - {label: tag, name: tag, widget: string}

